name: Check Templates

on:
  pull_request:
    branches:
      - 'DO-**'
    paths:
      - 'Values/**'
      - 'Charts/**'
      - 'scripts/**'

jobs:
  checkTemplates:
    runs-on: [self-hosted, linux, x64]
    steps:        
    - name: Checkout tools repo
      uses: actions/checkout@v3

    # Update the image tag with the latest image version
    - name: check templates
      run: |
        scripts/checkTemplates.sh
